spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: http://localhost:8080/
          predicates:
            - Path=/users/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE/
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE/
          predicates:
            - Path=/ratings/**

      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8083/eureka
